### PR TITLE
Workload Identity Fixes

### PR DESCRIPTION
**Pull request by jeremiahL**
- Always extract workload identity information from the environment, regardless of if config is loaded from secret or from file.
- Do not attempt to validate or fetch storage account keys if Workload Identity is chosen as authorization type.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes edgecache workload identity issues, including both some long-standing and some introduce with latest upstream pull.

**Which issue(s) this PR fixes**:
DevOps: 26417071, 26271462 and likely 26383537, though I haven't been able to test the last one yet.

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Review by silindbl-msft — APPROVED** [review]

**Comment by silindbl-msft** [comment]
I didn't review the chart changes (since it's hard to discern a diff), but the go portion looks good to me!

**Review by joe-atzinger — APPROVED** [review]
lgtm

**Review by pleaseDefine — APPROVED** [review]

**Review by ghost — APPROVED** [review]
This looks fine to me.

There are some CVEs, though: https://github.com/avoltz/blob-csi-driver/actions/runs/7507246135/job/20440389191

**Comment by jeremiahL** [comment]
> This looks fine to me.
> 
> There are some CVEs, though: https://github.com/avoltz/blob-csi-driver/actions/runs/7507246135/job/20440389191

The latest revision, that check actually came back clean.

**Pull request merged**
